server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: webflux
  data:
    mongodb:
      uri: mongodb://localhost:27017/webflux
  r2dbc:
    # 由springmvc的jdbc协议变为了r2dbcs协议连接 （ Reactive Relational Database Connectivity） ?serverTimezone=GMT%2B8
    url: r2dbcs:mysql://localhost:3306/test?serverZoneId=Asia/Shanghai
    username: root
    password: root123
